wp-content/themes/core/templates/page.html
wp-content/themes/core/templates/single.html

This was a fun (and frustrating) bug to track down- if “Inner blocks use content width” is disabled on Post Content then root blocks in the post editor won't have wide/full alignment controls
This fix updates the `page.html` and `single.html` templates to allow blocks supporting align wide and align full to appear in the block toolbar.
**Screenshots**:
- Without constrained layout, align options don't appear in block toolbar - http://p.tri.be/i/PV2rkF
- WITH constrained layout, align options reappear in block toolbar - http://p.tri.be/i/xZpLnu

Bugfix: Allow use of align wide and full

---

CHANGELOG.md
wp-content/plugins/core/src/Theme_Config/Theme_Config_Subscriber.php

Removes default support for XML-RPC authentication.  If the project requires it, we will enable it. In practice, we should have a really good reason why we need it.  Chances are really good that the Rest API can handle what is needed.

Removes default support for XML-RPC Auth

---

composer.json

[MOOSE-40]: Upgrade to WordPress core 6.2.2

---

CHANGELOG.md
local-config-sample.php
wp-content/plugins/core/src/Core.php
wp-content/plugins/core/src/Integrations/ACF.php
wp-content/plugins/core/src/Integrations/Integrations_Subscriber.php

Adds the ability to hide the ACF menu item using the `HIDE_ACF_MENU` constant. This update also always hides the menu item if `wp_get_environment_type()` returns `'production'`. 
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-26)
- [Link to Video](http://p.tri.be/i/SssxOI)

[MOOSE-26]: Adds the ability to hide the ACF menu item

---

wp-content/plugins/core/src/Blocks/Blocks_Subscriber.php
wp-content/themes/core/assets/pcss/layout/default.pcss
wp-content/themes/core/assets/pcss/media/_mixins.pcss
wp-content/themes/core/blocks/core/button/admin.js
wp-content/themes/core/blocks/core/button/editor.pcss
wp-content/themes/core/blocks/core/button/index.js
wp-content/themes/core/blocks/core/lists/Lists.php

- fixes issue with core block styles not enqueuing in the admin
- fixes issue with full-width blocks blocking editors from being able to easily add blocks to the bottom of the editor window just by clicking (just add some space to the bottom of `.editor-styles-wrapper`).
- fixes issue with floated images essentially disappearing from content if using the "content size" width
- unregistered some styles from the core button block
- removes admin styles from the core button block (easy enough to add back in and we moved away from having admin files for core blocks that didn't need them)
- fixes list styles not properly pulling in because of the difference in the core block name/slug.

Misc Fixes

---

wp-content/plugins/core/src/Assets/Admin_Assets_Enqueuer.php

- renames `admin` admin scripts to `tribe-admin` to avoid reserved word declarations. I think we fixed this on QCHI but it must not have made it's way back over to Moose. I'll be updating this on Careforth as well.
- Found on Careforth in the styleguide ticket: https://moderntribe.atlassian.net/browse/SNRLNK-88

[FIX] Rename admin styles / scripts to `tribe-admin` to avoid reserved words

---

wp-content/themes/core/templates/404.html

- adds a simple 404 page template
- 404 page template can be edited by the client under Appearance > Editor > Templates > 404
- our template should only be used as a starting point. We can update the template in code if we feel strong enough about saving an updated version of the 404 as the "default" but it's easy enough to update across environments that I don't think it's such a big deal. 
- [MOOSE-37](https://moderntribe.atlassian.net/browse/MOOSE-37)
- [Screenshot](http://p.tri.be/i/JZSTrq)
[MOOSE-37]: https://moderntribe.atlassian.net/browse/MOOSE-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOOSE-37] 404 template

---

wp-content/themes/core/assets/pcss/layout/default.pcss

Ran into an issue on Careforth where it wasn't clear that the layout style rules are needed only when `settings.layout.wideSize` is a fluid value, not fixed.
Moose has a fluid value for wideSize, so it makes sense to keep the rules. I've updated the comments so it's more clear they can be removed if it's a static value.
- [Link to Screencast overview](http://p.tri.be/v/yh3QcA)

Update layout style rule comments 

---

composer.json
composer.lock

- updates Block Editor Custom Alignments plugin to 1.0.6 to fix some issues

[CHORE] Update Block Editor Custom Alignments to 1.0.6

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/assets/pcss/typography/_mixins.pcss
wp-content/themes/core/blocks/tribe/post-permalink/block.json
wp-content/themes/core/blocks/tribe/post-permalink/edit.js
wp-content/themes/core/blocks/tribe/post-permalink/index.js
wp-content/themes/core/blocks/tribe/post-permalink/render.php
wp-content/themes/core/blocks/tribe/post-permalink/style.pcss
wp-content/themes/core/patterns/card-post-search-result.php

**NOTE: [This PR](https://github.com/moderntribe/moose/pull/61) & [this PR](https://github.com/moderntribe/moose/pull/63) should be reviewed before this one. This one adds on top of them.**
- adds Post Permalink custom block that displays the post permalink as text. Possible we should add `aria-hidden` here so it's not read?
- updates Post Type Name block with support for margin/padding
- updates Search Result Post Card pattern with the two new blocks
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-47)
- FE Screenshot: http://p.tri.be/i/7Pbs5i
- BE Screenshot: http://p.tri.be/i/nmyOwz

[MOOSE-47] Post Permalink Custom Block

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/blocks/tribe/query-results-count/block.json
wp-content/themes/core/blocks/tribe/query-results-count/edit.js
wp-content/themes/core/blocks/tribe/query-results-count/index.js
wp-content/themes/core/blocks/tribe/query-results-count/render.php
wp-content/themes/core/blocks/tribe/query-results-count/style.pcss
wp-content/themes/core/templates/search.html

**NOTE: This PR is dependent on 3 other PRs: [Post Card Patterns](https://github.com/moderntribe/moose/pull/61), [Post Type Name Custom Block](https://github.com/moderntribe/moose/pull/63), [Post Permalink Custom Block](https://github.com/moderntribe/moose/pull/64).**
- adds Query Results Count Block
- only works on archives / search templates. It doesn't seem possible to get query block contexts in inner blocks. This may be what Justin was mentioned on QCHI at one point. 
- if on the Search page, will check for the search query and append that onto the results count.
- otherwise, will just display "x results" (this can be easily updated) 
- seems to always display "0 results" in the editor (likely because we don't have the `$wp_query` context)
- updates Search Results template with new …

[MOOSE-48] Query Results Count Block

---

wp-content/plugins/core/src/Blocks/Block_Registrar.php

- Use `register_block_type_from_metadata` function (instead of `register_block_type`, which relies on the "name") for registering blocks since we're registering via the `block.json` file. `register_block_type` should work, but it makes a bit more sense to use the function that specifically is looking for the `block.json` file.

[FIX] update block registration function

---

wp-content/themes/core/templates/search.html

- finalizes search results template that was started in the post card pattern PRs.
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-36)

[MOOSE-36] Search Results Template

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/assets/pcss/global/reset.pcss
wp-content/themes/core/blocks/core/search/Search.php
wp-content/themes/core/blocks/core/search/index.js
wp-content/themes/core/blocks/core/search/style.pcss
wp-content/themes/core/blocks/tribe/query-results-count/render.php
wp-content/themes/core/blocks/tribe/query-results-count/style.pcss
wp-content/themes/core/parts/pagination.html
wp-content/themes/core/templates/search.html

- adds global reset for removing the default browser "X" (clear) button in search inputs that always confuse QA
- update post results count block to actually pull the total posts (pagination included)
- hide post results count block on the search results page if there are no results
- removes pagination template and moved it to the search template itself - this was causing issues with the pagination where it wouldn't receive the query context when using "inherit" queries.
- updates "no results" template according to the new design - unfortunately I can't get the search term in there without a custom block and I don't think that's super necessary for this
- **NOTE: WordPress still has an issue with the last page showing the No Results template if the last page only has one result.**
Links …

[MOOSE-36] Search Results Template QA

---

.env.sample
.gitignore
README.md
auth-sample.json
composer.json
composer.lock

Adds a platform option to the composer config to make sure even if you run composer using a different version of php, it will still download for 8.1. 
Changes the composer require for ACF to the [recommended version by WP Engine](https://www.advancedcustomfields.com/resources/installing-acf-pro-with-composer/).

Update Composer Platform and ACF Require

---

wp-content/plugins/core/src/Theme_Config/Theme_Support.php
wp-content/themes/core/blocks/core/lists/style.pcss
wp-content/themes/core/theme.json

- remove block styles support
- update items in styleguide that don't quite match after removing styles

[FIX] WP 6.3 Block Styles Support

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/blocks/core/pullquote/Pullquote.php
wp-content/themes/core/blocks/core/pullquote/index.js
wp-content/themes/core/blocks/core/pullquote/style.pcss
wp-content/themes/core/blocks/core/quote/index.js
wp-content/themes/core/blocks/core/quote/style.pcss
wp-content/themes/core/patterns/styleguide.php
wp-content/themes/core/theme.json

- reworks styleguide pattern to be a little bit easier to read & work with, as well as updating all of the blocks to 6.3 so we no longer have any confusion with blocks using old formats.
- move typography for Pullquote & Quote block to a `css` option in `theme.json` - it appears that the `typography` settings for these blocks was being overridden by the Paragraph block. I don't know if it would be better to add the custom styles in our actual block styles or if this would be ok 🤔 

[FIX] Update Styleguide Pattern for WP 6.3

---

wp-content/plugins/core/src/Assets/Editor_Assets_Enqueuer.php
wp-content/plugins/core/src/Blocks/Block_Base.php
wp-content/plugins/core/src/Blocks/Blocks_Subscriber.php
wp-content/themes/core/assets/pcss/editor.pcss
wp-content/themes/core/assets/pcss/global/reset.pcss

Fixes for asset enqueues with all the different contexts:
* Theme styles being properly loaded on the public website as well as the different editor contexts: post editor (inline or iframe) and site editor.
* Editor-only styles & scripts being properly loaded for both editors & contexts.
A couple things to address yet:
* I think we should go ahead and create a separate reset.pcss for the editor (or just reset styles we need to specifically?) rather than using our public reset.pcss in that context. It's not a blocker right now, but something we could address later.
* The `file_get_contents()` call used for inlining the styles is probably not the exact right approach. I think we need to adjust that for WPVIP's file system, correct?
- [Link to …

Asset enqueue refactor

---

CHANGELOG.md
composer.json
composer.lock
wp-content/plugins/core/src/Templates/Traits/Primary_Term.php

Switches out Yoast SEO for [Rank Math SEO](https://wordpress.org/plugins/seo-by-rank-math/), a bit of a newer SEO plugin for WordPress. In our early evaluations, Rank Math has a better UI, more features, and an importer from Yoast SEO if you want to move an existing project from Yoast to Rank Math.
We'll chat about this at the next Engineering Bi-weekly.

Replace Yoast SEO with Rank Math SEO

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/assets/pcss/cards/post.pcss
wp-content/themes/core/blocks/core/lists/style.pcss
wp-content/themes/core/blocks/core/posttemplate/style.pcss
wp-content/themes/core/blocks/core/querynoresults/Query_No_Results.php
wp-content/themes/core/blocks/core/querynoresults/index.js
wp-content/themes/core/blocks/core/querynoresults/style.pcss
wp-content/themes/core/blocks/core/querypagination/style.pcss
wp-content/themes/core/blocks/tribe/query-results-count/style.pcss
wp-content/themes/core/templates/archive.html
wp-content/themes/core/templates/index.html
wp-content/themes/core/templates/search.html

- Adds "Query No Results" block support so that we can add a "hack" to remove the no results block on the search template where we actually have results but it's the last page (thanks for finding this one @jamiepaul)
- Moves post card responsive to container queries, which should make the responsive for these cards feel a lot better.
- Adds explanations to the list block selectors
- The post template block was affected negatively by the asset enqueuing update. The selectors weren't specific enough to override some WP styling. I've added a `.wp-site-blocks` prefix to these selectors. @dpellenwood, I was incorrect on the list note from the other PR. `wp-site-blocks` is a child element of `editor-styles-wrapper`, so we _are_ able to also use that as a selector in the editor. The list block …

[MOOSE-34] Misc Template Fixes

---

wp-content/plugins/core/src/Post_Types/Post/Post.php
wp-content/plugins/core/src/Templates/Traits/Primary_Term.php

- adds `Primary_Term` trait to `Post` class so it can be used if necessary.
- fixes small issue with RankMath `get_post_meta` call in `Primary_Term` trait.

[FIX] Primary Term Trait

---

.deploy/config/local-config-dokku.php
composer.json
composer.lock
phpcs.xml.dist
wp-content/plugins/core/src/Assets/Admin_Assets_Enqueuer.php
wp-content/plugins/core/src/Core.php
wp-content/themes/core/blocks/tribe/post-permalink/render.php
wp-content/themes/core/blocks/tribe/post-type-name/render.php
wp-content/themes/core/blocks/tribe/query-results-count/render.php
wp-content/themes/core/blocks/tribe/terms/render.php

Upgrades default PHP Version for PHPCS to 8 to match our current minimum suggested PHP Version.
Adds escaping for `get_block_wrapper_attributes()` using `wp_kses_data()`.
Removes unused plugins from Composer.

PHPCS Cleanup

---

CHANGELOG.md
composer.json
composer.lock

Updates WordPress Core from 6.3.1 to 6.3.2
Updates the following plugins:
- advanced-custom-fields-pro to 6.2.1.1
- disable-emojis to 1.7.6
- limit-login-attempts-reloaded to 2.25.25
- seo-by-rank-math to 1.0.203

WordPress 6.3.2 and Plugin Updates

---

.github/lighthouse/lighthouserc.json
.github/workflows/lighthouse-ci.yml

Due to a limitation in GitHub actions, this will need to be merged to the main branch before running the workflow as a full test.
This PR creates a Lighthouse CI Action that can be run via a workflow_dispatch. When the workflow runs, it will query one to many (line separated) of the URLs listed in the `urls` param.  The results will trigger an error or warning in the action UI based on the config settings in the `lighthouserc.json` file.  These settings should be customized for each production site based on the current performance. The full report is also added to the action artifacts, which can be disabled by changing the `uploadArtifacts` param to false.
This action aims to eventually run after deployments to test the site and trigger notifications if there are any performance, …

Adds Lighthouse CI GitHub Action

---

.gitignore
CHANGELOG.md

Updates the .gitignore to exclude only the root folder node_modules and not all the node_modules folders it finds in the project.  
**Jira Ticket:**  [MOOSE-67](https://moderntribe.atlassian.net/browse/MOOSE-67)
[MOOSE-67]: https://moderntribe.atlassian.net/browse/MOOSE-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOOSE-67]: Exclude only the root node_modules folder

---

wp-content/themes/core/blocks/core/column/editor.js

- fixes an issue where an extra div was being added to the Column block causing any Columns block layout other than 50/50 to not display correctly.

[FIX] Mobile Column Stacking Order

---

.lando.yml
CHANGELOG.md

Adds the ability to trigger xdebug with wp-cli when using lando. Requires `lando rebuild` to go into effect on current projects.

Adds override for triggering xdebug with using WP-CLI

---

CHANGELOG.md
composer.json
composer.lock

Update WP Core to 6.4.2 and the following plugins:
```
+---------------------------------+-----------+----------------+
| name                            | update    | update_version |
+---------------------------------+-----------+----------------+
| advanced-custom-fields-pro      | available | 6.2.4          |
| duracelltomi-google-tag-manager | available | 1.19           |
| seo-by-rank-math                | available | 1.0.208.1      |
| safe-svg                        | available | 2.2.2          |
| user-switching                  | available | 1.7.2          |
+---------------------------------+-----------+----------------+
```

Chore: Update WordPress to 6.4.2 and available plugins

---

wp-content/themes/core/assets/pcss/actions/_variables.pcss
wp-content/themes/core/assets/pcss/color/_variables.pcss
wp-content/themes/core/blocks/core/button/_variables.pcss
wp-content/themes/core/blocks/core/querypagination/style.pcss
wp-content/themes/core/theme.json

Change primary and secondary color names to the name of the colors.
The use of `primary` and `secondary` as Brand color names did not fit with all projects.
I did not change the use of Primary and Secondary as a name for button style variations.
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-51)

[MOOSE-51]: Color Names

---

webpack.config.js

- rewrites `blockEntryPoints` function to allow `view.js` files to generate within blocks
- since all entry point loops are the same, we can just use one array & loop to handle all cases
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-86)
- `files` array upon running `npm run dist`: http://p.tri.be/i/7mV7gs (`console.log` has been removed)

[MOOSE-86] Allow `view.js` files for blocks

---

wp-content/plugins/core/src/Blocks/Block_Registrar.php

- updates ACF block `render_template` functions to provide ACF blocks with more useful information that we weren't providing previously
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-81)

[MOOSE-81] Update ACF Block `render_template` Function

---

CHANGELOG.md
wp-content/themes/core/assets/pcss/editor.pcss
wp-content/themes/core/assets/pcss/global/editor.pcss

- adds styling to the WP title bar to differentiate it from the other blocks on the page
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-111)
- Old: http://p.tri.be/i/o4R4w5
- New: http://p.tri.be/i/KlYSKe

[MOOSE-111] Editor Title Bar

---

CHANGELOG.md
wp-content/plugins/core/src/Blocks/Terms_Block.php
wp-content/themes/core/blocks/tribe/terms/block.json
wp-content/themes/core/blocks/tribe/terms/edit.js

- fixes issue where the Terms block would error when no post ID was provided to it
- sets defaults for attributes in the Terms block - should prevent any "missing attribute" issues
- since the `taxonomies` array is gathered by an async request, we should be checking if it exists before we loop over nothing.
- [Link to Panopto Slack thread](https://tribe.slack.com/archives/C061UC7B2F9/p1710250320818599)

[FIX] Terms Block

---

CHANGELOG.md
wp-content/themes/core/assets/pcss/editor.pcss
wp-content/themes/core/assets/pcss/layout/default.pcss
wp-content/themes/core/assets/pcss/layout/editor.pcss
wp-content/themes/core/theme.json

- migrates layout updates from Panopto (and a few other projects) to properly split FE / editor layout styling
- moves to using static values for content, wide, and (added) grid width alignment settings
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-84)

[MOOSE-84] Layout Settings

---

package-lock.json
package.json

- Some NPM packages didn't seem to update properly on my last PR #149 . Doing that again.
- Updated the supported browsers to remove remove Safari exceptions. [iOS 16 versions are now well under 5% usage in the US](https://gs.statcounter.com/ios-version-market-share/all/united-states-of-america). Note that this change is also reflected on our public [Testing Policy](https://tri.be/testing-policy/).
- [MOOSE-140](https://moderntribe.atlassian.net/browse/MOOSE-140)
[MOOSE-140]: https://moderntribe.atlassian.net/browse/MOOSE-140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOOSE-140] Updates: browserlist supported browser & npm packages

---

tests/_data/editor_asset_test.php
tests/acceptance/ExampleCest.php
tests/wpunit/BlockBaseWpUnitTest.php
wp-content/plugins/core/src/Blocks/Block_Base.php

Add version to the editor styles to allow cache busting
Add example stub for acceptance tests.The `Cest` is correct terminology here. Codecept use such names in order to find tests
Add simple testing for grabbing editor styles meta from file 
- https://moderntribe.atlassian.net/browse/MOOSE-114

BE: Update editor style enqueues to use a version param to allow cache busting

---

.github/workflows/code-quality.yml

Our code quality checks aren't running on PR sync, but we expect them to pass before a PR can be merged.

Add PR sync as a trigger for code quality checks.

---

.gitignore
.phpstorm.meta.php
wp-content/plugins/core/src/Theme_Config/Theme_Support.php

Block themes already apply most traditional theme_support features in WordPress.  From [FSE.com:](https://fullsiteediting.com/lessons/creating-block-based-themes/#h-theme-support)
> The following theme support is automatically enabled for block themes:
> post-thumbnails, editor-styles, responsive-embeds, automatic-feed-links, html5 styles, and html5 scripts.
> 
> You do not need to include `add_theme_support( 'title-tag' )` in the setup function, because WordPress already renders the title tag for full site editing themes.
And, adding `title-tag` theme  support actually causes [a bug in Yoast SEO to surface](https://tribe.slack.com/archives/C01CY7418GY/p1732200411511529) where the title is erroneously injected twice into each document.
This PR removes unnecessary `add_theme_support()` …

Fix/moose 169/remove unnecessary theme support calls

---

.lando.yml
composer.json
composer.lock
wp-content/mu-plugins/force-plugin-activation.php

- Updates Lando PHP version to 8.3
- Updates Lando database container to MariaDB 10.11 as the default, 10.3 is no longer a supported version. *NOTE:* This is a breaking change. Existing local dev environments should do a `lando db-export` before pulling this change.
- Disables Mailhog containers by default as they cause an error on lando start. See the code for more info.
- Removes the WP Tota11y plugin as a composer dep since it's not used.
- Moves WP Debug plugin to a regular composer require so it's available in Dokku envs (I could be persuaded to remove this entirely)
- Bumps the PHP version in composer.json to 8.3.
- [MOOSE-171](https://moderntribe.atlassian.net/browse/MOOSE-171)
[MOOSE-171]: https://moderntribe.atlassian.net/browse/MOOSE-171?atlOrigin=eyJpIjo …

Chore/moose 171/lando updates

---

package.json

- migrates an update from learn.tri.be that fixed an issue where the `package.json` linting script could try to lint other `package.json` files that were checked into the repo. The script should now _only_ check the `package.json` file that we define in the core theme. 
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-153)
- Confirming script is working on correct `package.json` file: http://p.tri.be/i/aw6VIN

[MOOSE-153]: lint only core theme package.json

---

CHANGELOG.md
wp-content/themes/core/assets/pcss/layout/_variables.pcss
wp-content/themes/core/blocks/core/table/style.pcss

- adds content width as a layout variable
- sets `min-width` on table elements within Table blocks. As the comment states, this is the only way to actually apply the `overflow-x` set on the Table block for tables that have minimal content. 
- I'll put this one through DQA so designers can confirm what minimum width they'd like to see.
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-181)
- Mobile table view: http://p.tri.be/i/AzzZSr

[MOOSE-181] Table Overflow

---

CHANGELOG.md
wp-content/plugins/core/src/Core.php
wp-content/plugins/core/src/Menus/Admin_Menu_Order.php
wp-content/plugins/core/src/Menus/Menu_Order.php
wp-content/plugins/core/src/Menus/Menu_Subscriber.php
wp-content/plugins/core/src/Post_Types/Training/Config.php

Please note I do not know if this is the best way to go about this. The only other way I could think of would be to awkwardly handle reordering all the menu item priorities, which would get super messy IMO. 
This PR assumes that newly created CPTs would need to be manually added to the menu order array in the correct spot.
- reorder menu items via `menu_order` filter. 
- update Training Docs menu item label
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-172)
- Updated menu order: http://p.tri.be/i/42Jcpi

[MOOSE-172] Admin Menu Cleanup

---

CHANGELOG.md

- missed a changelog entry for the details block changes

[MOOSE-179]: changelog for details block update

---

wp-content/themes/core/assets/js/utils/create-wp-controls.js
wp-content/themes/core/blocks/core/column/editor.js

- Updates Column block `stackingOrder` attribute to be a `number` field to prevent type mismatching when checking / applying the value
- When using `toggle` control types, you previously weren't able to set the `defaultValue` to `true` as there were incorrect checks in place. These checks have been updated to ensure that the `number` and `select` control types continue to function, and the toggle control can now function as it was supposed to. We should now be properly checking if the `toggle` control is set to `true` before applying the class / style rules, instead of just applying them if the value was different than the default. 
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-193)

[MOOSE-193] Create WP Controls Script Fixes

---

wp-config-environment.php

We often need to load composer's main autoloader file for different class maps and containers to work. However, we no longer use a `.env` file to store composer auth secrets. This change always requires the composer autoloader.php file if it's accessible.
The whitespace changes were to align with our current linting.

Always require composer's autoloader if it's available. 

---

wp-content/themes/core/assets/pcss/parts/footer.pcss
wp-content/themes/core/assets/pcss/typography/_variables.pcss

This fixes a misnamed CSS variable. Note that `--font-weight-regular` is already being used in [our mixins](https://github.com/search?q=repo%3Amoderntribe%2Fmoose%20--font-weight-regular&type=code) although it wasn't defined.

Fix misnamed typography variables

---

.github/workflows/pipeline-dokku.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Replace deprecated `::set-output`

---

CHANGELOG.md
wp-content/themes/core/assets/pcss/global/reset.pcss
wp-content/themes/core/bindings/Query_Results_Count.php
wp-content/themes/core/blocks/core/querypagination/style.pcss
wp-content/themes/core/templates/search.html

- fixes issues where `iframe` elements display in the editor (pattern / template previews) were getting overwritten by the inclusion of the reset in the editor CSS
- updates Query Results Count binding to not display any content when there aren't any results
- update pagination styling
- update search results template
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-212)
- Search Results: http://p.tri.be/i/rd3gAU
- Updated pagination: http://p.tri.be/i/1YYMPe
- Mobile: http://p.tri.be/i/6kY1Ic
- No results: http://p.tri.be/i/2tW3nd

[MOOSE-212] Search Template

---

local-config-sample.php

- Defines development mode constant to aide with pattern caching in local development. [See this comment for more explanation.](https://github.com/moderntribe/moose/pull/206#issuecomment-3075719887)

Define WP_DEVELOPMENT_MODE to disable pattern caching

---

wp-content/plugins/core/src/Assets/Admin_Assets_Enqueuer.php

prevents a fatal error on the login page if ACF isn't activated. This is due to ACF Pro being removed as a force-activated plugin in #200 .

Bug fix: Don't try to use `get_field()` if ACF isn't activated.

---

package-lock.json
package.json
wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/blocks/tribe/logo-marquee/block.json
wp-content/themes/core/blocks/tribe/logo-marquee/edit.js
wp-content/themes/core/blocks/tribe/logo-marquee/editor.pcss
wp-content/themes/core/blocks/tribe/logo-marquee/index.js
wp-content/themes/core/blocks/tribe/logo-marquee/save.js
wp-content/themes/core/blocks/tribe/logo-marquee/style.pcss
wp-content/themes/core/blocks/tribe/logo-marquee/view.js

Import the Logo Marquee block created by @tylermachado into 🫎.
This PR includes two enhancements to the original block:
- Updates the block to display all logos in the editor when selected (uses a grid layout for easier editing).
- Adds drag-and-drop functionality to reorder logos directly in the editor using [dnd-kit](https://docs.dndkit.com/).
It adds two dependencies:
```
"dependencies": {
"@dnd-kit/core": "^6.3.1",
"@dnd-kit/sortable": "^10.0.0",
"@dnd-kit/utilities": "^3.2.2",
"@wordpress/icons": "^10.23.0",
"imagesloaded": "^5.0.0"
},
```
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-248)
- [Link to Video](https://www.loom.com/share/c6a91b07ba00496785e6a53333d10de7?sid=bca0c803-27fc-4fb3-9d71-c027b4748b47)

[MOOSE-248] Logo marquee custom block

---

.phpstorm.meta.php
CHANGELOG.md
browsersync.config.js
lefthook.yml
phpcs.xml.dist
wp-config.php

- adds FE linting to pre-commit hook
- this won't prevent some of the issues @spadilha was seeing with indenting and code editor specific things (maybe we need to look at our editor config?)
- I specifically _chose_ to not run `--fix` on these FE hooks. I want developers to specifically see mistakes and actively correct them before committing their changes
- moved all lefthook commands to jobs to allow us to name and prevent them from running if there are no files in the commit with the types necessary to run the command
- `phpstan` still runs on everything in the project but only runs if there are PHP changes in the commit
- note here that any top-level file has to be called specifically as lefthook's `glob` doesn't recognize `./*.js` (etc...) as a valid selector
- updates PHP & WP …

[MOOSE-257] FE Linting Pre-Commit Hook

---

postcss.config.js
wp-content/themes/core/blocks/tribe/rating-stars/icons.pcss
wp-content/themes/core/blocks/tribe/rating-stars/icons/icon-star-empty.svg
wp-content/themes/core/blocks/tribe/rating-stars/icons/icon-star-full.svg
wp-content/themes/core/blocks/tribe/rating-stars/icons/icon-star-half.svg
wp-content/themes/core/blocks/tribe/rating-stars/style.pcss

This pull request updates how SVG icons are loaded and styled for the Rating Stars block, improving maintainability and theme compatibility. The main changes include configuring PostCSS to support inline SVGs from the new icons directory, defining SVG icons as CSS variables, and refactoring the block’s styling to use CSS masks instead of background images.
**SVG Icon Loading and Configuration**
* Updated `postcss.config.js` to include the `blocks/tribe/rating-stars/icons` directory for inline SVG processing, enabling the use of custom star icons in the block styles.
**Block Styling Refactor**
* Defined SVG icons (`star-full`, `star-half`, `star-empty`) using `@svg-load` and set them as CSS variables for easy reference and theming.
* Refactored the `.star--full`, `.star--half`, and …

[MOOSE-239]: Use svg-load and update dark-mode
