.lando.yml
README.md
composer.json
composer.lock
local-config-sample.php
phpcs.xml.dist

Adds the ability to run with [Lando](https://lando.dev/).
Updates the `readme.md` for details on backend setup, and local environments.

Adds Lando for local development 

---

.editorconfig
.prettierignore
.stylelintrc.json
browsersync.config.js
package-lock.json
package.json
postcss.config.js
webpack.config.js
wp-content/themes/core/assets/pcss/print.pcss
wp-content/themes/core/blocks/core/button/editor.pcss
wp-content/themes/core/blocks/core/button/style.pcss

Updates the FE build tooling and packages per our learnin's on QCHI.

Update build to latest per QCHI.

---

composer.json
composer.lock
wp-content/mu-plugins/force-plugin-activation.php

There was a refactor by StellarWP on the Force Plugin Activation. This brings that functionality into the plugin using our plugin list.

Force Plugin Activation Refactor to 2.0

---

wp-content/themes/core/index.php
wp-content/themes/core/style.css

Updates the theme to have an `index.php`
Updates the Theme Name to Moose because I want to stay away from using SquareTwo
- [Error when loading](http://p.tri.be/i/59Bvmr)

Adds an index.php file

---

.github/workflows/php-tests.yml

I am trying to fix an error when running php-test workflows on main.

PHP-Tests Fix

---

package-lock.json

Update engines in package-lock as it didn't get done with my updates branch.

---

wp-content/themes/core/theme.json

- update `caption` default color
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-8)

[MOOSE-8] QA Fixes

---

wp-content/plugins/core/src/Core.php
wp-content/plugins/core/src/Post_Types/Page/Config.php
wp-content/plugins/core/src/Post_Types/Page/Page.php
wp-content/plugins/core/src/Post_Types/Page/Page_Subscriber.php
wp-content/themes/core/patterns/page-placeholder.php
wp-content/themes/core/patterns/page.php
wp-content/themes/core/templates/page.html

- updates Page template to match designs
- it's probably likely that the page title element in this template would need to be removed completely on most sites. Maybe it makes sense to exclude it from the template and only have the Post Content block?
- [MOOSE-33](https://moderntribe.atlassian.net/browse/MOOSE-33)
- [Screenshot](http://p.tri.be/i/4jIkzh)
[MOOSE-33]: https://moderntribe.atlassian.net/browse/MOOSE-33?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MOOSE-33] Page Template

---

wp-content/themes/core/style.css

* Update theme name to be more client-friendly
* Update MT legal name
* Update minimum required WordPress version

Theme metadata update

---

wp-content/plugins/core/src/Theme_Config/Theme_Config_Subscriber.php

- Tyla noticed in QA that the excerpt was surrounding itself with the square brackets, this has been updated.
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-38)
- http://p.tri.be/i/P4Goql

[MOOSE-38] Post Cards QA

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/deploy-stage.yml
.github/workflows/php-tests.yml
.github/workflows/phpcs.yml
.github/workflows/static-analysis.yml
.github/workflows/workflows.yml
CHANGELOG.md
wp-content/plugins/core/src/Core.php

Updates the deploy systems to use auth.json for composer authentication.

Update deploy system to use auth.json for ACF

---

.github/workflows/dokku-dev.yml
.github/workflows/dokku-review-app.yml
.github/workflows/pipeline-dokku.yml

Update Dokku to use the auth.json for composer installing ACF.

Setup dokku for auth.json

---

wp-content/themes/core/assets/pcss/global/reset.pcss
wp-content/themes/core/blocks/core/lists/style.pcss
wp-content/themes/core/blocks/core/pullquote/style.pcss
wp-content/themes/core/blocks/core/quote/style.pcss
wp-content/themes/core/patterns/styleguide.php
wp-content/themes/core/theme.json

- updates paragraphs, headings, to have global spacing
- removes margin definitions from reset
- fixes lists to ensure list styles don't get applied to other blocks
- updates styleguide pattern to remove extra spacers that were used to create space 
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-32)

[MOOSE-32] Post Single QA

---

.gitignore

Just what the title says, adds VS Code workspace file to gitignore.

Add VS Code workspace file to gitignore

---

composer.json

- updates WP to 6.5 (RC4 for now)

[CHORE] Update WP to 6.5

---

composer.json

[CHORE] WP 6.7

---

.eslintrc.json
CHANGELOG.md

- updates ESLint config to include browser env variable like `MutationObserver` or `IntersectionObserver`.
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-177)

[MOOSE-177] eslint config update

---

composer.json
composer.lock
package-lock.json
package.json
wp-content/mu-plugins/force-plugin-activation.php

Update to WordPress 6.8. Also handles a number of baseline package updates.
- [MOOSE-195](https://moderntribe.atlassian.net/browse/MOOSE-195)
[MOOSE-195]: https://moderntribe.atlassian.net/browse/MOOSE-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feature/wordpress 6.8

---

wp-content/themes/core/parts/footer.html

We are already creating a footer tag in the page template. Registering another in the footer pattern creates a second, nested footer tag.

Duplicate footer tag

---

wp-content/themes/core/templates/404.html

- updates paragraph text on 404 template to match updated designs
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-211?focusedCommentId=176473)

[MOOSE-211] 404 Template DQA

---

wp-content/plugins/core/src/Blocks/Blocks_Definer.php
wp-content/themes/core/assets/pcss/typography/_mixins.pcss
wp-content/themes/core/blocks/core/postauthor/Post_Author.php
wp-content/themes/core/blocks/core/postauthor/index.js
wp-content/themes/core/blocks/core/postauthor/style.pcss
wp-content/themes/core/blocks/core/postauthorname/style.pcss
wp-content/themes/core/patterns/post.php
wp-content/themes/core/theme.json

This update aligns the default Post Single template with the [Figma design](https://www.figma.com/design/X4XME8L48tb3IoucXVhdEU/Moose-Website-Design-System-2.0?node-id=7804-10348&t=9N1yUSR6yvpr8PVs-4).
- Adds custom styles for the `core/post-author` block
- Removes uppercase styling from taxonomy terms globally
- Removes bold styling from tags globally
- Styles the Single Post author footer section
- Updates global pullquote styles to match Figma
- Adds `blockGap` to the `outermost/social-sharing` block
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-236)
- [Link to Video](https://www.loom.com/share/53a7b0f63ded47c99d857faac8b22ebd?sid=b9707392-4ad9-4f74-9c1b-4d01dae5a683)

[MOOSE-236]: Update Simple Post Single Template to Match Design

---

wp-content/themes/core/patterns/post.php

Increase social-share icons to "normal" size.
- [Link to Issue](https://moderntribe.atlassian.net/browse/MOOSE-236)

[MOOSE-236]: Bump up share icons to normal size

---

package.json
wp-content/themes/core/blocks/tribe/icon-picker/icons/icons-list.js
wp-content/themes/core/blocks/tribe/icon-picker/scripts/cleanup-components.js
wp-content/themes/core/blocks/tribe/icon-picker/scripts/generate-icons-list.js

It fixes case mismatches and key formatting for icon components.

[MOOSE-204]: Fix case mismatches
